import Head from 'next/head';
import Container from '../../components/Container';
import { useTranslation } from 'next-i18next';
import { GetStaticProps } from 'next/types';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import ProjectItem from '../../components/ProjectItem';
import { useSelector } from 'react-redux';
import { AppState } from '../../store/store';

export default function ProfilePage() {
  // hook
  const { t } = useTranslation('index');

  // state
  const projectState = useSelector((state) => (state as AppState).projectState);

  return (
    <>
      <Head>
        <title>{t('title')}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-hidden relative dark:bg-gray-800">
        <div className="h-24 w-full bg-transparent"></div>
        <div className="h-4 w-full bg-transparent"></div>
        <Container className="flex justify-center gap-8">
          <div id="projects-section" className="flex flex-col gap-4 w-full">
            {Object.values(projectState.projects).map((project, idx) => (
              <ProjectItem project={project} key={idx}></ProjectItem>
            ))}
          </div>
        </Container>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale ?? 'han', ['project']))
  }
});
