import Head from 'next/head';
import Image from 'next/image';
import { clsx } from 'clsx';
import style from '/styles/Intro.module.css';
import Container from '../components/Container';
import Button, { ButtonType } from '../components/Button';
import Router from 'next/router';
import Link from 'next/link';

export default function ProfilePage({ className }: { className: string }) {
  return (
    <>
      <Head>
        <title>Introduction of WuBlog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex-grow flex flex-col">
        <div className="h-24 w-full bg-transparent"></div>
        <Container className="flex flex-col items-center justify-center gap-4 flex-grow">
          <div className="font-medium text-xl">404 / There Is Nothing.</div>

          <Link href={'/'} legacyBehavior>
            <Button variant={ButtonType.secondary}>Back To Home.</Button>
          </Link>
        </Container>
      </main>
    </>
  );
}
